
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/j9_hello_quotes
    username: ironhacker
    password: 1r0nh4ck3r2022!*Blu
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true # show the commands that are being executed
    #    generate-ddl : true
    hibernate:
      ddl-auto: create # create, create-drop, validate, none, update ....
  profiles:
    active: demo